app.blueprints.divisions = {
  about: 'About',
  bindings: 'Bindings',
  binding_target: 'Binding target',
  compute_service: 'Compute service',
  // configuration: 'Configuration',
  dimensions: 'Dimensions',
  images: 'Images',
  // input: 'Input',
  managed_packages: 'Managed packages',
  bundled_packages: 'Bundled packages',
  permissions: 'Permissions',
  ports: 'Ports',
  provider: 'Provider',
  // repositories: 'Repositories',
  resources: 'Resources',
  // service_tasks: 'Service tasks',
  system_packages: 'System packages',
  volumes: 'Volumes',
}
