app.blueprints.divisions = {
  about: 'About',
  bindings: 'Bindings',
  binding_target: 'Binding target',
  compute_service: 'Compute service',
  // configuration: 'Configuration',
  dimensions: 'Dimensions',
  images: 'Images',
  // input: 'Input',
  modules: 'Modules',
  other_packages: 'Other packages',
  permissions: 'Permissions',
  ports: 'Ports',
  provider: 'Provider',
  // repositories: 'Repositories',
  resources: 'Resources',
  // service_tasks: 'Service tasks',
  system_packages: 'System packages',
  volumes: 'Volumes',
}
